MOUSEKEY_ENABLE = yes        # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no        # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
AUDIO_ENABLE = no           # Audio output
VIA_ENABLE = no
LTO_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
EXTRAFLAGS += -flto
COMBO_ENABLE = yes
SRC += features/achordion.c